# Generated by Django 5.1.1 on 2024-09-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0003_alter_appuser_groups_alter_appuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='votingApp.upload'),
        ),
    ]
